services:
 db:
   image: mysql:latest
   container_name: telemetryDevContainer
   ports:
     - "3307:3306"
   environment:
     - MYSQL_ROOT_PASSWORD=${DB_DEV_PASSWORD}
     - MYSQL_DATABASE=${DB_DEV_NAME}
   volumes:
     - ./mysql_data:/var/lib/mysql